// Open the cinema page, then pass this function to playwright-cli run-code.
async page => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.reload();
  if (!(await page.locator('.cinema-card[data-collection="true"]').count())) throw Error('Missing film collections');
  if (await page.locator('.cinema-card[data-type="series"]').count() !== 54) throw Error('Series count');
  if (await page.locator('nav[aria-label="Screen categories"]').innerText().then(t => /[·・]/.test(t))) throw Error('Navigation separators');
  if (await page.locator('main h2').count()) throw Error('Section headings remain');
  const killBill = page.locator('.cinema-card').filter({ has: page.getByRole('heading', { name: 'Kill Bill', exact: true }) });
  await killBill.click();
  if (await page.locator('[data-installment]').count() !== 2) throw Error('Kill Bill must have two films in one modal');
  await page.locator('[data-installment="1"]').click();
  if (await page.locator('#modal-content-slot img').getAttribute('alt') !== 'Kill Bill: Vol. 2') throw Error('Installment did not change');
  if ((await page.locator('#modal-content-slot h2').innerText()).trim() !== 'Kill Bill: Vol. 2\n杀死比尔2') throw Error('Film heading must use the selected installment without repeating its English name');
  if (await page.locator('#modal-right-scroll-pane h3').count()) throw Error('Duplicate movie title above review');
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.getElementById('cinema-modal-backdrop').classList.contains('pointer-events-none'));
  await page.getByRole('button', { name: 'Animation', exact: true }).click();
  if (!(await page.locator('#section-animation .cinema-card:visible').count())) throw Error('Animation missing');
  if (await page.locator('#section-films').isVisible()) throw Error('Films should be hidden');
  await page.locator('[data-item-id="tv-45790"]').click();
  await page.locator('[data-installment="1"]').click();
  if (await page.locator('.season-watch-record').count()) throw Error('Empty JoJo record titles must not appear');
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.getElementById('cinema-modal-backdrop').classList.contains('pointer-events-none'));
  await page.locator('[data-item-id="tv-46260"]').click();
  if (await page.locator('[data-installment]').count() !== 2) throw Error('Naruto must contain only the original and Shippuden');
  await page.locator('[data-installment="1"]').click();
  if (!(await page.locator('#modal-content-slot').innerText()).includes('500 EPISODES')) throw Error('Shippuden must show its complete episode count');
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.getElementById('cinema-modal-backdrop').classList.contains('pointer-events-none'));
  await page.locator('[data-item-id="tv-95479"]').click();
  if (!(await page.locator('#modal-content-slot').innerText()).includes('ORIGINAL WORK')) throw Error('Credit role must distinguish original author from director');
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.getElementById('cinema-modal-backdrop').classList.contains('pointer-events-none'));
  await page.getByRole('button', { name: 'Series', exact: true }).click();
  if (await page.locator('#section-animation').isVisible()) throw Error('Animation should be hidden');
  const office = page.locator('.cinema-card[data-item-id="tv-2316"]');
  await office.click();
  await page.waitForFunction(() => getComputedStyle(document.getElementById('cinema-modal-container')).opacity === '1' && getComputedStyle(document.getElementById('cinema-modal-backdrop')).opacity === '1');
  if (await page.locator('[data-installment]').count() !== 9) throw Error('Office must have nine selectable seasons');
  const firstPoster = await page.locator('#modal-content-slot img').getAttribute('src');
  await page.locator('[data-installment="1"]').click();
  if (await page.locator('#modal-content-slot img').getAttribute('src') === firstPoster) throw Error('Season poster did not switch');
  const names = await page.locator('[data-installment]').allTextContents();
  if (!names.every((s, i) => s.trim() === `Season ${i + 1}`)) throw Error('Season switcher must show names only');
  if (!(await page.locator('#modal-content-slot').innerText()).includes('2026-09-07')) throw Error('Selected season watch date must remain in details');
  await page.waitForFunction(() => [...document.querySelectorAll('#modal-content-slot img')].every(i => i.complete && i.naturalWidth));
  await page.screenshot({ path: 'output/playwright/cinema-series-desktop.png' });
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.getElementById('cinema-modal-backdrop').classList.contains('pointer-events-none'));
  await page.setViewportSize({ width: 390, height: 844 });
  await office.click();
  await page.waitForFunction(() => getComputedStyle(document.getElementById('cinema-modal-container')).opacity === '1' && getComputedStyle(document.getElementById('cinema-modal-backdrop')).opacity === '1');
  if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw Error('Horizontal overflow');
  await page.screenshot({ path: 'output/playwright/cinema-series-mobile.png' });
  await page.keyboard.press('Escape');
  return { series: 54, officeSeasons: 9, dates: 'passed', modal: 'passed', mobile: 'passed' };
}
